project_id       = "proyecto-mlops-504619"
dataset_fuente   = "BaseDatosIris"
table_train      = "iris-train"
table_test       = "iris-test"
dataset_final    = "Resultados"
table_prediction = "predictions"
region           = "US"

service_account        = "vertex-processing@proyecto-mlops-504619.iam.gserviceaccount.com"
project_id_fuente      = "proyecto-fuente"
project_id_produccion  = "proyecto-produccion-505720"
